# Make sure to check the documentation at https://goreleaser.com
version: 2
builds:
  - id: quorum
    env:
      - CGO_ENABLED=0
    main: main.go
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    ldflags: >
      -s
      -w
      -X main.GitCommit={{.ShortCommit}}
    hooks:
      post: sh -c 'command -v upx >/dev/null && find dist -name "quorum*" -type f -print0 | xargs -n 1 -0 upx || true'

dockers_v2:
  - id: quorum
    ids:
      - quorum
    images:
      - ghcr.io/rumsystem/{{ .ProjectName }}
    tags:
      - "{{ .Version }}"
      - latest
    dockerfile: Dockerfile-goreleaser
    platforms:
      - linux/amd64
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.url: "https://github.com/rumsystem/{{ .ProjectName }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: '{{ time "2006-01-02T15:04:05Z07:00" }}'
      org.opencontainers.image.revision: "{{ .FullCommit }}"

archives:
  - formats:
      - tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats:
          - zip
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
release:
  github:
    owner: rumsystem
    name: quorum
  prerelease: auto # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
