// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: chain.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TrxType int32

const (
	TrxType_REQ_SIGN            TrxType = 0 // request witness sign
	TrxType_REQ_SIGN_RESP       TrxType = 1 // response requset withness sign
	TrxType_ADD_NEW_BLOCK       TrxType = 2 // new block created
	TrxType_ADD_NEW_BLOCK_RESP  TrxType = 3 // response new block created
	TrxType_REQ_NEXT_BLOCK      TrxType = 4 // request next block
	TrxType_REQ_NEXT_BLOCK_RESP TrxType = 5 // response request next block
	TrxType_PEER_ANNOUNCE       TrxType = 6 // announce I am online
)

// Enum value maps for TrxType.
var (
	TrxType_name = map[int32]string{
		0: "REQ_SIGN",
		1: "REQ_SIGN_RESP",
		2: "ADD_NEW_BLOCK",
		3: "ADD_NEW_BLOCK_RESP",
		4: "REQ_NEXT_BLOCK",
		5: "REQ_NEXT_BLOCK_RESP",
		6: "PEER_ANNOUNCE",
	}
	TrxType_value = map[string]int32{
		"REQ_SIGN":            0,
		"REQ_SIGN_RESP":       1,
		"ADD_NEW_BLOCK":       2,
		"ADD_NEW_BLOCK_RESP":  3,
		"REQ_NEXT_BLOCK":      4,
		"REQ_NEXT_BLOCK_RESP": 5,
		"PEER_ANNOUNCE":       6,
	}
)

func (x TrxType) Enum() *TrxType {
	p := new(TrxType)
	*p = x
	return p
}

func (x TrxType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrxType) Descriptor() protoreflect.EnumDescriptor {
	return file_chain_proto_enumTypes[0].Descriptor()
}

func (TrxType) Type() protoreflect.EnumType {
	return &file_chain_proto_enumTypes[0]
}

func (x TrxType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrxType.Descriptor instead.
func (TrxType) EnumDescriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{0}
}

type ReqBlock int32

const (
	ReqBlock_BLOCK_IN_TRX ReqBlock = 0 //block data in trx
	ReqBlock_BLOCK_ON_TOP ReqBlock = 1 //top block, no new block, block in trx is empty
)

// Enum value maps for ReqBlock.
var (
	ReqBlock_name = map[int32]string{
		0: "BLOCK_IN_TRX",
		1: "BLOCK_ON_TOP",
	}
	ReqBlock_value = map[string]int32{
		"BLOCK_IN_TRX": 0,
		"BLOCK_ON_TOP": 1,
	}
)

func (x ReqBlock) Enum() *ReqBlock {
	p := new(ReqBlock)
	*p = x
	return p
}

func (x ReqBlock) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqBlock) Descriptor() protoreflect.EnumDescriptor {
	return file_chain_proto_enumTypes[1].Descriptor()
}

func (ReqBlock) Type() protoreflect.EnumType {
	return &file_chain_proto_enumTypes[1]
}

func (x ReqBlock) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqBlock.Descriptor instead.
func (ReqBlock) EnumDescriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{1}
}

type TrxMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrxId     string  `protobuf:"bytes,1,opt,name=TrxId,proto3" json:"TrxId,omitempty"`
	GroupId   string  `protobuf:"bytes,2,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	MsgType   TrxType `protobuf:"varint,3,opt,name=MsgType,proto3,enum=quorum.pb.TrxType" json:"MsgType,omitempty"`
	Data      []byte  `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	Sender    string  `protobuf:"bytes,5,opt,name=Sender,proto3" json:"Sender,omitempty"`
	TimeStamp int64   `protobuf:"varint,6,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Version   string  `protobuf:"bytes,7,opt,name=Version,proto3" json:"Version,omitempty"`
	Pubkey    string  `protobuf:"bytes,8,opt,name=Pubkey,proto3" json:"Pubkey,omitempty"`
	Sign      []byte  `protobuf:"bytes,9,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *TrxMsg) Reset() {
	*x = TrxMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrxMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrxMsg) ProtoMessage() {}

func (x *TrxMsg) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrxMsg.ProtoReflect.Descriptor instead.
func (*TrxMsg) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{0}
}

func (x *TrxMsg) GetTrxId() string {
	if x != nil {
		return x.TrxId
	}
	return ""
}

func (x *TrxMsg) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *TrxMsg) GetMsgType() TrxType {
	if x != nil {
		return x.MsgType
	}
	return TrxType_REQ_SIGN
}

func (x *TrxMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TrxMsg) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TrxMsg) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *TrxMsg) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TrxMsg) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *TrxMsg) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type Trx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg       *TrxMsg  `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data      []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Consensus []string `protobuf:"bytes,3,rep,name=Consensus,proto3" json:"Consensus,omitempty"`
}

func (x *Trx) Reset() {
	*x = Trx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trx) ProtoMessage() {}

func (x *Trx) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trx.ProtoReflect.Descriptor instead.
func (*Trx) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{1}
}

func (x *Trx) GetMsg() *TrxMsg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Trx) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Trx) GetConsensus() []string {
	if x != nil {
		return x.Consensus
	}
	return nil
}

type ReqSign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datahash   []byte `protobuf:"bytes,1,opt,name=Datahash,proto3" json:"Datahash,omitempty"`
	Expiration string `protobuf:"bytes,2,opt,name=Expiration,proto3" json:"Expiration,omitempty"`
}

func (x *ReqSign) Reset() {
	*x = ReqSign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSign) ProtoMessage() {}

func (x *ReqSign) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSign.ProtoReflect.Descriptor instead.
func (*ReqSign) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{2}
}

func (x *ReqSign) GetDatahash() []byte {
	if x != nil {
		return x.Datahash
	}
	return nil
}

func (x *ReqSign) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

type ReqSignResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqTrxId    string `protobuf:"bytes,1,opt,name=ReqTrxId,proto3" json:"ReqTrxId,omitempty"`
	Requester   string `protobuf:"bytes,2,opt,name=Requester,proto3" json:"Requester,omitempty"`
	Witness     string `protobuf:"bytes,3,opt,name=Witness,proto3" json:"Witness,omitempty"`
	Hash        []byte `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
	WitnessSign []byte `protobuf:"bytes,5,opt,name=WitnessSign,proto3" json:"WitnessSign,omitempty"`
}

func (x *ReqSignResp) Reset() {
	*x = ReqSignResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSignResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSignResp) ProtoMessage() {}

func (x *ReqSignResp) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSignResp.ProtoReflect.Descriptor instead.
func (*ReqSignResp) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{3}
}

func (x *ReqSignResp) GetReqTrxId() string {
	if x != nil {
		return x.ReqTrxId
	}
	return ""
}

func (x *ReqSignResp) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

func (x *ReqSignResp) GetWitness() string {
	if x != nil {
		return x.Witness
	}
	return ""
}

func (x *ReqSignResp) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ReqSignResp) GetWitnessSign() []byte {
	if x != nil {
		return x.WitnessSign
	}
	return nil
}

type ReqNextBlockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provider  string   `protobuf:"bytes,1,opt,name=Provider,proto3" json:"Provider,omitempty"`
	Requester string   `protobuf:"bytes,2,opt,name=Requester,proto3" json:"Requester,omitempty"`
	Response  ReqBlock `protobuf:"varint,3,opt,name=Response,proto3,enum=quorum.pb.ReqBlock" json:"Response,omitempty"`
	BlockId   string   `protobuf:"bytes,4,opt,name=BlockId,proto3" json:"BlockId,omitempty"`
	Block     []byte   `protobuf:"bytes,5,opt,name=Block,proto3" json:"Block,omitempty"`
}

func (x *ReqNextBlockResp) Reset() {
	*x = ReqNextBlockResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqNextBlockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqNextBlockResp) ProtoMessage() {}

func (x *ReqNextBlockResp) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqNextBlockResp.ProtoReflect.Descriptor instead.
func (*ReqNextBlockResp) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{4}
}

func (x *ReqNextBlockResp) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ReqNextBlockResp) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

func (x *ReqNextBlockResp) GetResponse() ReqBlock {
	if x != nil {
		return x.Response
	}
	return ReqBlock_BLOCK_IN_TRX
}

func (x *ReqNextBlockResp) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *ReqNextBlockResp) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

var File_chain_proto protoreflect.FileDescriptor

var file_chain_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x71,
	0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62, 0x22, 0xf6, 0x01, 0x0a, 0x06, 0x54, 0x72, 0x78,
	0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x72, 0x78, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x72, 0x78, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x72, 0x78, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69, 0x67,
	0x6e, 0x22, 0x5c, 0x0a, 0x03, 0x54, 0x72, 0x78, 0x12, 0x23, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x72, 0x78, 0x4d, 0x73, 0x67, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x22,
	0x45, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61,
	0x74, 0x61, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x44, 0x61,
	0x74, 0x61, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x97, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x53, 0x69,
	0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x54, 0x72, 0x78,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x71, 0x54, 0x72, 0x78,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x57, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x57, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x20,
	0x0a, 0x0b, 0x57, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x57, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x69, 0x67, 0x6e,
	0x22, 0xad, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x4e, 0x65, 0x78, 0x74, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x2f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x71, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x2a, 0x95, 0x01, 0x0a, 0x07, 0x54, 0x72, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08,
	0x52, 0x45, 0x51, 0x5f, 0x53, 0x49, 0x47, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45,
	0x51, 0x5f, 0x53, 0x49, 0x47, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x01, 0x12, 0x11, 0x0a,
	0x0d, 0x41, 0x44, 0x44, 0x5f, 0x4e, 0x45, 0x57, 0x5f, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x10, 0x02,
	0x12, 0x16, 0x0a, 0x12, 0x41, 0x44, 0x44, 0x5f, 0x4e, 0x45, 0x57, 0x5f, 0x42, 0x4c, 0x4f, 0x43,
	0x4b, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x51, 0x5f,
	0x4e, 0x45, 0x58, 0x54, 0x5f, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13,
	0x52, 0x45, 0x51, 0x5f, 0x4e, 0x45, 0x58, 0x54, 0x5f, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x52,
	0x45, 0x53, 0x50, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x45, 0x45, 0x52, 0x5f, 0x41, 0x4e,
	0x4e, 0x4f, 0x55, 0x4e, 0x43, 0x45, 0x10, 0x06, 0x2a, 0x2e, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x49, 0x4e,
	0x5f, 0x54, 0x52, 0x58, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x5f,
	0x4f, 0x4e, 0x5f, 0x54, 0x4f, 0x50, 0x10, 0x01, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x75, 0x6f, 0x2d, 0x6a, 0x75, 0x2f, 0x71, 0x75,
	0x6f, 0x72, 0x75, 0x6d, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chain_proto_rawDescOnce sync.Once
	file_chain_proto_rawDescData = file_chain_proto_rawDesc
)

func file_chain_proto_rawDescGZIP() []byte {
	file_chain_proto_rawDescOnce.Do(func() {
		file_chain_proto_rawDescData = protoimpl.X.CompressGZIP(file_chain_proto_rawDescData)
	})
	return file_chain_proto_rawDescData
}

var file_chain_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chain_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_chain_proto_goTypes = []interface{}{
	(TrxType)(0),             // 0: quorum.pb.TrxType
	(ReqBlock)(0),            // 1: quorum.pb.ReqBlock
	(*TrxMsg)(nil),           // 2: quorum.pb.TrxMsg
	(*Trx)(nil),              // 3: quorum.pb.Trx
	(*ReqSign)(nil),          // 4: quorum.pb.ReqSign
	(*ReqSignResp)(nil),      // 5: quorum.pb.ReqSignResp
	(*ReqNextBlockResp)(nil), // 6: quorum.pb.ReqNextBlockResp
}
var file_chain_proto_depIdxs = []int32{
	0, // 0: quorum.pb.TrxMsg.MsgType:type_name -> quorum.pb.TrxType
	2, // 1: quorum.pb.Trx.Msg:type_name -> quorum.pb.TrxMsg
	1, // 2: quorum.pb.ReqNextBlockResp.Response:type_name -> quorum.pb.ReqBlock
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chain_proto_init() }
func file_chain_proto_init() {
	if File_chain_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chain_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrxMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chain_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chain_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chain_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSignResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chain_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqNextBlockResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chain_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chain_proto_goTypes,
		DependencyIndexes: file_chain_proto_depIdxs,
		EnumInfos:         file_chain_proto_enumTypes,
		MessageInfos:      file_chain_proto_msgTypes,
	}.Build()
	File_chain_proto = out.File
	file_chain_proto_rawDesc = nil
	file_chain_proto_goTypes = nil
	file_chain_proto_depIdxs = nil
}
