// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: rumexchange.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionMsgType int32

const (
	SessionMsgType_IF_CONN   SessionMsgType = 0
	SessionMsgType_CONN_RESP SessionMsgType = 1
)

// Enum value maps for SessionMsgType.
var (
	SessionMsgType_name = map[int32]string{
		0: "IF_CONN",
		1: "CONN_RESP",
	}
	SessionMsgType_value = map[string]int32{
		"IF_CONN":   0,
		"CONN_RESP": 1,
	}
)

func (x SessionMsgType) Enum() *SessionMsgType {
	p := new(SessionMsgType)
	*p = x
	return p
}

func (x SessionMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_rumexchange_proto_enumTypes[0].Descriptor()
}

func (SessionMsgType) Type() protoreflect.EnumType {
	return &file_rumexchange_proto_enumTypes[0]
}

func (x SessionMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionMsgType.Descriptor instead.
func (SessionMsgType) EnumDescriptor() ([]byte, []int) {
	return file_rumexchange_proto_rawDescGZIP(), []int{0}
}

type SessionMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType  SessionMsgType   `protobuf:"varint,1,opt,name=MsgType,proto3,enum=quorum.pb.SessionMsgType" json:"MsgType,omitempty"`
	IfConn   *SessionIfConn   `protobuf:"bytes,2,opt,name=IfConn,proto3,oneof" json:"IfConn,omitempty"`
	ConnResp *SessionConnResp `protobuf:"bytes,3,opt,name=ConnResp,proto3,oneof" json:"ConnResp,omitempty"`
}

func (x *SessionMsg) Reset() {
	*x = SessionMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rumexchange_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMsg) ProtoMessage() {}

func (x *SessionMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rumexchange_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMsg.ProtoReflect.Descriptor instead.
func (*SessionMsg) Descriptor() ([]byte, []int) {
	return file_rumexchange_proto_rawDescGZIP(), []int{0}
}

func (x *SessionMsg) GetMsgType() SessionMsgType {
	if x != nil {
		return x.MsgType
	}
	return SessionMsgType_IF_CONN
}

func (x *SessionMsg) GetIfConn() *SessionIfConn {
	if x != nil {
		return x.IfConn
	}
	return nil
}

func (x *SessionMsg) GetConnResp() *SessionConnResp {
	if x != nil {
		return x.ConnResp
	}
	return nil
}

type SessionIfConn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DestPeerID   []byte     `protobuf:"bytes,1,opt,name=DestPeerID,proto3" json:"DestPeerID,omitempty"`
	SrcPeerID    []byte     `protobuf:"bytes,2,opt,name=SrcPeerID,proto3" json:"SrcPeerID,omitempty"`
	SessionToken []byte     `protobuf:"bytes,3,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
	Signature    []byte     `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"` //sign by the srcPeer
	Peersroutes  []*PeerSig `protobuf:"bytes,5,rep,name=Peersroutes,proto3" json:"Peersroutes,omitempty"`
}

func (x *SessionIfConn) Reset() {
	*x = SessionIfConn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rumexchange_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionIfConn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionIfConn) ProtoMessage() {}

func (x *SessionIfConn) ProtoReflect() protoreflect.Message {
	mi := &file_rumexchange_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionIfConn.ProtoReflect.Descriptor instead.
func (*SessionIfConn) Descriptor() ([]byte, []int) {
	return file_rumexchange_proto_rawDescGZIP(), []int{1}
}

func (x *SessionIfConn) GetDestPeerID() []byte {
	if x != nil {
		return x.DestPeerID
	}
	return nil
}

func (x *SessionIfConn) GetSrcPeerID() []byte {
	if x != nil {
		return x.SrcPeerID
	}
	return nil
}

func (x *SessionIfConn) GetSessionToken() []byte {
	if x != nil {
		return x.SessionToken
	}
	return nil
}

func (x *SessionIfConn) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SessionIfConn) GetPeersroutes() []*PeerSig {
	if x != nil {
		return x.Peersroutes
	}
	return nil
}

type SessionConnResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DestPeerID   []byte     `protobuf:"bytes,1,opt,name=DestPeerID,proto3" json:"DestPeerID,omitempty"`
	SrcPeerID    []byte     `protobuf:"bytes,2,opt,name=SrcPeerID,proto3" json:"SrcPeerID,omitempty"`
	SessionToken []byte     `protobuf:"bytes,3,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
	Signature    []byte     `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"` //sign by the destPeer
	ChannelId    string     `protobuf:"bytes,5,opt,name=ChannelId,proto3" json:"ChannelId,omitempty"`
	Peersroutes  []*PeerSig `protobuf:"bytes,6,rep,name=Peersroutes,proto3" json:"Peersroutes,omitempty"`
}

func (x *SessionConnResp) Reset() {
	*x = SessionConnResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rumexchange_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionConnResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConnResp) ProtoMessage() {}

func (x *SessionConnResp) ProtoReflect() protoreflect.Message {
	mi := &file_rumexchange_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConnResp.ProtoReflect.Descriptor instead.
func (*SessionConnResp) Descriptor() ([]byte, []int) {
	return file_rumexchange_proto_rawDescGZIP(), []int{2}
}

func (x *SessionConnResp) GetDestPeerID() []byte {
	if x != nil {
		return x.DestPeerID
	}
	return nil
}

func (x *SessionConnResp) GetSrcPeerID() []byte {
	if x != nil {
		return x.SrcPeerID
	}
	return nil
}

func (x *SessionConnResp) GetSessionToken() []byte {
	if x != nil {
		return x.SessionToken
	}
	return nil
}

func (x *SessionConnResp) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SessionConnResp) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SessionConnResp) GetPeersroutes() []*PeerSig {
	if x != nil {
		return x.Peersroutes
	}
	return nil
}

type PeerSig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId     []byte `protobuf:"bytes,1,opt,name=PeerId,proto3" json:"PeerId,omitempty"`
	SessionSig []byte `protobuf:"bytes,2,opt,name=SessionSig,proto3" json:"SessionSig,omitempty"`
}

func (x *PeerSig) Reset() {
	*x = PeerSig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rumexchange_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerSig) ProtoMessage() {}

func (x *PeerSig) ProtoReflect() protoreflect.Message {
	mi := &file_rumexchange_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerSig.ProtoReflect.Descriptor instead.
func (*PeerSig) Descriptor() ([]byte, []int) {
	return file_rumexchange_proto_rawDescGZIP(), []int{3}
}

func (x *PeerSig) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *PeerSig) GetSessionSig() []byte {
	if x != nil {
		return x.SessionSig
	}
	return nil
}

var File_rumexchange_proto protoreflect.FileDescriptor

var file_rumexchange_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x75, 0x6d, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62, 0x22, 0xcd,
	0x01, 0x0a, 0x0a, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x33, 0x0a,
	0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x49, 0x66, 0x43, 0x6f, 0x6e, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x66, 0x43, 0x6f, 0x6e, 0x6e, 0x48, 0x00, 0x52, 0x06,
	0x49, 0x66, 0x43, 0x6f, 0x6e, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x3b, 0x0a, 0x08, 0x43, 0x6f, 0x6e,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x71, 0x75,
	0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x48, 0x01, 0x52, 0x08, 0x43, 0x6f, 0x6e, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x49, 0x66, 0x43, 0x6f, 0x6e,
	0x6e, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0xc5,
	0x01, 0x0a, 0x0d, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x66, 0x43, 0x6f, 0x6e, 0x6e,
	0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x44, 0x65, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x1c, 0x0a, 0x09, 0x53, 0x72, 0x63, 0x50, 0x65, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x53, 0x72, 0x63, 0x50, 0x65, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22,
	0x0a, 0x0c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x34, 0x0a, 0x0b, 0x50, 0x65, 0x65, 0x72, 0x73, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x53, 0x69, 0x67, 0x52, 0x0b, 0x50, 0x65, 0x65, 0x72, 0x73,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x22, 0xe5, 0x01, 0x0a, 0x0f, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65,
	0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x44, 0x65, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x72,
	0x63, 0x50, 0x65, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x53,
	0x72, 0x63, 0x50, 0x65, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x0b, 0x50, 0x65, 0x65, 0x72,
	0x73, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x53, 0x69,
	0x67, 0x52, 0x0b, 0x50, 0x65, 0x65, 0x72, 0x73, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x22, 0x41,
	0x0a, 0x07, 0x50, 0x65, 0x65, 0x72, 0x53, 0x69, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x65, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x50, 0x65, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x69,
	0x67, 0x2a, 0x2c, 0x0a, 0x0e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x46, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4e, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x01, 0x42,
	0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x75,
	0x6d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rumexchange_proto_rawDescOnce sync.Once
	file_rumexchange_proto_rawDescData = file_rumexchange_proto_rawDesc
)

func file_rumexchange_proto_rawDescGZIP() []byte {
	file_rumexchange_proto_rawDescOnce.Do(func() {
		file_rumexchange_proto_rawDescData = protoimpl.X.CompressGZIP(file_rumexchange_proto_rawDescData)
	})
	return file_rumexchange_proto_rawDescData
}

var file_rumexchange_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rumexchange_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rumexchange_proto_goTypes = []interface{}{
	(SessionMsgType)(0),     // 0: quorum.pb.SessionMsgType
	(*SessionMsg)(nil),      // 1: quorum.pb.SessionMsg
	(*SessionIfConn)(nil),   // 2: quorum.pb.SessionIfConn
	(*SessionConnResp)(nil), // 3: quorum.pb.SessionConnResp
	(*PeerSig)(nil),         // 4: quorum.pb.PeerSig
}
var file_rumexchange_proto_depIdxs = []int32{
	0, // 0: quorum.pb.SessionMsg.MsgType:type_name -> quorum.pb.SessionMsgType
	2, // 1: quorum.pb.SessionMsg.IfConn:type_name -> quorum.pb.SessionIfConn
	3, // 2: quorum.pb.SessionMsg.ConnResp:type_name -> quorum.pb.SessionConnResp
	4, // 3: quorum.pb.SessionIfConn.Peersroutes:type_name -> quorum.pb.PeerSig
	4, // 4: quorum.pb.SessionConnResp.Peersroutes:type_name -> quorum.pb.PeerSig
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_rumexchange_proto_init() }
func file_rumexchange_proto_init() {
	if File_rumexchange_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rumexchange_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rumexchange_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionIfConn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rumexchange_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionConnResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rumexchange_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerSig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rumexchange_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rumexchange_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rumexchange_proto_goTypes,
		DependencyIndexes: file_rumexchange_proto_depIdxs,
		EnumInfos:         file_rumexchange_proto_enumTypes,
		MessageInfos:      file_rumexchange_proto_msgTypes,
	}.Build()
	File_rumexchange_proto = out.File
	file_rumexchange_proto_rawDesc = nil
	file_rumexchange_proto_goTypes = nil
	file_rumexchange_proto_depIdxs = nil
}
