// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: chain.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrxType int32

const (
	TrxType_REQ_SIGN            TrxType = 0 // request witness sign
	TrxType_REQ_SIGN_RESP       TrxType = 1 // response requset withness sign
	TrxType_ADD_NEW_BLOCK       TrxType = 2 // new block created
	TrxType_ADD_NEW_BLOCK_RESP  TrxType = 3 // response new block created
	TrxType_REQ_NEXT_BLOCK      TrxType = 4 // request next block
	TrxType_REQ_NEXT_BLOCK_RESP TrxType = 5 // response request next block
	TrxType_PEER_ANNOUNCE       TrxType = 6 // announce I am online
)

// Enum value maps for TrxType.
var (
	TrxType_name = map[int32]string{
		0: "REQ_SIGN",
		1: "REQ_SIGN_RESP",
		2: "ADD_NEW_BLOCK",
		3: "ADD_NEW_BLOCK_RESP",
		4: "REQ_NEXT_BLOCK",
		5: "REQ_NEXT_BLOCK_RESP",
		6: "PEER_ANNOUNCE",
	}
	TrxType_value = map[string]int32{
		"REQ_SIGN":            0,
		"REQ_SIGN_RESP":       1,
		"ADD_NEW_BLOCK":       2,
		"ADD_NEW_BLOCK_RESP":  3,
		"REQ_NEXT_BLOCK":      4,
		"REQ_NEXT_BLOCK_RESP": 5,
		"PEER_ANNOUNCE":       6,
	}
)

func (x TrxType) Enum() *TrxType {
	p := new(TrxType)
	*p = x
	return p
}

func (x TrxType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrxType) Descriptor() protoreflect.EnumDescriptor {
	return file_chain_proto_enumTypes[0].Descriptor()
}

func (TrxType) Type() protoreflect.EnumType {
	return &file_chain_proto_enumTypes[0]
}

func (x TrxType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrxType.Descriptor instead.
func (TrxType) EnumDescriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{0}
}

type ReqBlock int32

const (
	ReqBlock_BLOCK_IN_TRX ReqBlock = 0 //block data in trx
	ReqBlock_BLOCK_ON_TOP ReqBlock = 1 //top block, no new block, block in trx is empty
)

// Enum value maps for ReqBlock.
var (
	ReqBlock_name = map[int32]string{
		0: "BLOCK_IN_TRX",
		1: "BLOCK_ON_TOP",
	}
	ReqBlock_value = map[string]int32{
		"BLOCK_IN_TRX": 0,
		"BLOCK_ON_TOP": 1,
	}
)

func (x ReqBlock) Enum() *ReqBlock {
	p := new(ReqBlock)
	*p = x
	return p
}

func (x ReqBlock) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqBlock) Descriptor() protoreflect.EnumDescriptor {
	return file_chain_proto_enumTypes[1].Descriptor()
}

func (ReqBlock) Type() protoreflect.EnumType {
	return &file_chain_proto_enumTypes[1]
}

func (x ReqBlock) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqBlock.Descriptor instead.
func (ReqBlock) EnumDescriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{1}
}

type TrxMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrxId     string  `protobuf:"bytes,1,opt,name=TrxId,json=trxId,proto3" json:"TrxId,omitempty"`
	GroupId   string  `protobuf:"bytes,2,opt,name=GroupId,json=groupId,proto3" json:"GroupId,omitempty"`
	MsgType   TrxType `protobuf:"varint,3,opt,name=MsgType,json=msgType,proto3,enum=quorum.pb.TrxType" json:"MsgType,omitempty"`
	Data      []byte  `protobuf:"bytes,4,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	Sender    string  `protobuf:"bytes,5,opt,name=Sender,json=sender,proto3" json:"Sender,omitempty"`
	TimeStamp int64   `protobuf:"varint,6,opt,name=TimeStamp,json=timeStamp,proto3" json:"TimeStamp,omitempty"`
	Version   string  `protobuf:"bytes,7,opt,name=Version,json=version,proto3" json:"Version,omitempty"`
	Pubkey    string  `protobuf:"bytes,8,opt,name=Pubkey,json=pubkey,proto3" json:"Pubkey,omitempty"`
	Sign      []byte  `protobuf:"bytes,9,opt,name=Sign,json=sign,proto3" json:"Sign,omitempty"`
}

func (x *TrxMsg) Reset() {
	*x = TrxMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrxMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrxMsg) ProtoMessage() {}

func (x *TrxMsg) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrxMsg.ProtoReflect.Descriptor instead.
func (*TrxMsg) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{0}
}

func (x *TrxMsg) GetTrxId() string {
	if x != nil {
		return x.TrxId
	}
	return ""
}

func (x *TrxMsg) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *TrxMsg) GetMsgType() TrxType {
	if x != nil {
		return x.MsgType
	}
	return TrxType_REQ_SIGN
}

func (x *TrxMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TrxMsg) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TrxMsg) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *TrxMsg) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TrxMsg) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *TrxMsg) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type Trx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg       *TrxMsg  `protobuf:"bytes,1,opt,name=Msg,json=msg,proto3" json:"Msg,omitempty"`
	Data      []byte   `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	Consensus []string `protobuf:"bytes,3,rep,name=Consensus,json=consensus,proto3" json:"Consensus,omitempty"`
}

func (x *Trx) Reset() {
	*x = Trx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trx) ProtoMessage() {}

func (x *Trx) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trx.ProtoReflect.Descriptor instead.
func (*Trx) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{1}
}

func (x *Trx) GetMsg() *TrxMsg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Trx) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Trx) GetConsensus() []string {
	if x != nil {
		return x.Consensus
	}
	return nil
}

type ReqSign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datahash   []byte `protobuf:"bytes,1,opt,name=Datahash,json=datahash,proto3" json:"Datahash,omitempty"`
	Expiration string `protobuf:"bytes,2,opt,name=Expiration,json=expiration,proto3" json:"Expiration,omitempty"`
}

func (x *ReqSign) Reset() {
	*x = ReqSign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSign) ProtoMessage() {}

func (x *ReqSign) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSign.ProtoReflect.Descriptor instead.
func (*ReqSign) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{2}
}

func (x *ReqSign) GetDatahash() []byte {
	if x != nil {
		return x.Datahash
	}
	return nil
}

func (x *ReqSign) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

type ReqSignResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqTrxId    string `protobuf:"bytes,1,opt,name=ReqTrxId,json=reqTrxId,proto3" json:"ReqTrxId,omitempty"`
	Requester   string `protobuf:"bytes,2,opt,name=Requester,json=requester,proto3" json:"Requester,omitempty"`
	Witness     string `protobuf:"bytes,3,opt,name=Witness,json=witness,proto3" json:"Witness,omitempty"`
	Hash        []byte `protobuf:"bytes,4,opt,name=Hash,json=hash,proto3" json:"Hash,omitempty"`
	WitnessSign []byte `protobuf:"bytes,5,opt,name=WitnessSign,json=witnessSign,proto3" json:"WitnessSign,omitempty"`
}

func (x *ReqSignResp) Reset() {
	*x = ReqSignResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSignResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSignResp) ProtoMessage() {}

func (x *ReqSignResp) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSignResp.ProtoReflect.Descriptor instead.
func (*ReqSignResp) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{3}
}

func (x *ReqSignResp) GetReqTrxId() string {
	if x != nil {
		return x.ReqTrxId
	}
	return ""
}

func (x *ReqSignResp) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

func (x *ReqSignResp) GetWitness() string {
	if x != nil {
		return x.Witness
	}
	return ""
}

func (x *ReqSignResp) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ReqSignResp) GetWitnessSign() []byte {
	if x != nil {
		return x.WitnessSign
	}
	return nil
}

type ReqNextBlockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provider  string   `protobuf:"bytes,1,opt,name=Provider,json=provider,proto3" json:"Provider,omitempty"`
	Requester string   `protobuf:"bytes,2,opt,name=Requester,json=requester,proto3" json:"Requester,omitempty"`
	Response  ReqBlock `protobuf:"varint,3,opt,name=Response,json=response,proto3,enum=quorum.pb.ReqBlock" json:"Response,omitempty"`
	BlockId   string   `protobuf:"bytes,4,opt,name=BlockId,json=blockId,proto3" json:"BlockId,omitempty"`
	Block     []byte   `protobuf:"bytes,5,opt,name=Block,json=block,proto3" json:"Block,omitempty"`
}

func (x *ReqNextBlockResp) Reset() {
	*x = ReqNextBlockResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqNextBlockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqNextBlockResp) ProtoMessage() {}

func (x *ReqNextBlockResp) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqNextBlockResp.ProtoReflect.Descriptor instead.
func (*ReqNextBlockResp) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{4}
}

func (x *ReqNextBlockResp) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ReqNextBlockResp) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

func (x *ReqNextBlockResp) GetResponse() ReqBlock {
	if x != nil {
		return x.Response
	}
	return ReqBlock_BLOCK_IN_TRX
}

func (x *ReqNextBlockResp) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *ReqNextBlockResp) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid          string `protobuf:"bytes,1,opt,name=Cid,json=cid,proto3" json:"Cid,omitempty"`
	GroupId      string `protobuf:"bytes,2,opt,name=GroupId,json=groupId,proto3" json:"GroupId,omitempty"`
	PrevBlockId  string `protobuf:"bytes,3,opt,name=PrevBlockId,json=prevBlockId,proto3" json:"PrevBlockId,omitempty"`
	BlockNum     int64  `protobuf:"varint,4,opt,name=BlockNum,json=blockNum,proto3" json:"BlockNum,omitempty"`
	Timestamp    int64  `protobuf:"varint,5,opt,name=Timestamp,json=timestamp,proto3" json:"Timestamp,omitempty"`
	Hash         string `protobuf:"bytes,6,opt,name=Hash,json=hash,proto3" json:"Hash,omitempty"`
	PreviousHash string `protobuf:"bytes,7,opt,name=PreviousHash,json=previousHash,proto3" json:"PreviousHash,omitempty"`
	Producer     string `protobuf:"bytes,8,opt,name=Producer,json=producer,proto3" json:"Producer,omitempty"`
	Signature    string `protobuf:"bytes,9,opt,name=Signature,json=signature,proto3" json:"Signature,omitempty"`
	Trxs         []*Trx `protobuf:"bytes,10,rep,name=Trxs,json=trxs,proto3" json:"Trxs,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{5}
}

func (x *Block) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Block) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Block) GetPrevBlockId() string {
	if x != nil {
		return x.PrevBlockId
	}
	return ""
}

func (x *Block) GetBlockNum() int64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *Block) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Block) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Block) GetPreviousHash() string {
	if x != nil {
		return x.PreviousHash
	}
	return ""
}

func (x *Block) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *Block) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Block) GetTrxs() []*Trx {
	if x != nil {
		return x.Trxs
	}
	return nil
}

type NewBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Producer string `protobuf:"bytes,1,opt,name=Producer,json=producer,proto3" json:"Producer,omitempty"`
	BlockId  string `protobuf:"bytes,2,opt,name=BlockId,json=blockId,proto3" json:"BlockId,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=Data,json=data,proto3" json:"Data,omitempty"` //the whole block
}

func (x *NewBlock) Reset() {
	*x = NewBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBlock) ProtoMessage() {}

func (x *NewBlock) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBlock.ProtoReflect.Descriptor instead.
func (*NewBlock) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{6}
}

func (x *NewBlock) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *NewBlock) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *NewBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type NewBlockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Producer        string `protobuf:"bytes,1,opt,name=Producer,json=producer,proto3" json:"Producer,omitempty"`
	BlockId         string `protobuf:"bytes,2,opt,name=BlockId,json=blockId,proto3" json:"BlockId,omitempty"`
	StorageProvider string `protobuf:"bytes,3,opt,name=StorageProvider,json=storageProvider,proto3" json:"StorageProvider,omitempty"`
}

func (x *NewBlockResp) Reset() {
	*x = NewBlockResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewBlockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBlockResp) ProtoMessage() {}

func (x *NewBlockResp) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBlockResp.ProtoReflect.Descriptor instead.
func (*NewBlockResp) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{7}
}

func (x *NewBlockResp) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *NewBlockResp) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *NewBlockResp) GetStorageProvider() string {
	if x != nil {
		return x.StorageProvider
	}
	return ""
}

type ReqNextBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockId string `protobuf:"bytes,1,opt,name=BlockId,json=blockId,proto3" json:"BlockId,omitempty"` //block id
}

func (x *ReqNextBlock) Reset() {
	*x = ReqNextBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqNextBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqNextBlock) ProtoMessage() {}

func (x *ReqNextBlock) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqNextBlock.ProtoReflect.Descriptor instead.
func (*ReqNextBlock) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{8}
}

func (x *ReqNextBlock) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

type GroupItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerPubKey    string `protobuf:"bytes,1,opt,name=OwnerPubKey,json=ownerPubKey,proto3" json:"OwnerPubKey,omitempty"`
	GroupId        string `protobuf:"bytes,2,opt,name=GroupId,json=groupId,proto3" json:"GroupId,omitempty"`
	GroupName      string `protobuf:"bytes,3,opt,name=GroupName,json=groupName,proto3" json:"GroupName,omitempty"`
	LastUpdate     int64  `protobuf:"varint,4,opt,name=LastUpdate,json=lastUpdate,proto3" json:"LastUpdate,omitempty"`
	LatestBlockNum int64  `protobuf:"varint,5,opt,name=LatestBlockNum,json=latestBlockNum,proto3" json:"LatestBlockNum,omitempty"`
	LatestBlockId  string `protobuf:"bytes,6,opt,name=LatestBlockId,json=latestBlockId,proto3" json:"LatestBlockId,omitempty"`
	GenesisBlock   *Block `protobuf:"bytes,7,opt,name=GenesisBlock,json=genesisBlock,proto3" json:"GenesisBlock,omitempty"`
}

func (x *GroupItem) Reset() {
	*x = GroupItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupItem) ProtoMessage() {}

func (x *GroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupItem.ProtoReflect.Descriptor instead.
func (*GroupItem) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{9}
}

func (x *GroupItem) GetOwnerPubKey() string {
	if x != nil {
		return x.OwnerPubKey
	}
	return ""
}

func (x *GroupItem) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupItem) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupItem) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

func (x *GroupItem) GetLatestBlockNum() int64 {
	if x != nil {
		return x.LatestBlockNum
	}
	return 0
}

func (x *GroupItem) GetLatestBlockId() string {
	if x != nil {
		return x.LatestBlockId
	}
	return ""
}

func (x *GroupItem) GetGenesisBlock() *Block {
	if x != nil {
		return x.GenesisBlock
	}
	return nil
}

type GroupContentItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrxId     string `protobuf:"bytes,1,opt,name=TrxId,json=trxId,proto3" json:"TrxId,omitempty"`
	Publisher string `protobuf:"bytes,2,opt,name=Publisher,json=publisher,proto3" json:"Publisher,omitempty"`
	Content   []byte `protobuf:"bytes,3,opt,name=Content,json=content,proto3" json:"Content,omitempty"`
	TimeStamp int64  `protobuf:"varint,4,opt,name=TimeStamp,json=timeStamp,proto3" json:"TimeStamp,omitempty"`
}

func (x *GroupContentItem) Reset() {
	*x = GroupContentItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupContentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupContentItem) ProtoMessage() {}

func (x *GroupContentItem) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupContentItem.ProtoReflect.Descriptor instead.
func (*GroupContentItem) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{10}
}

func (x *GroupContentItem) GetTrxId() string {
	if x != nil {
		return x.TrxId
	}
	return ""
}

func (x *GroupContentItem) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *GroupContentItem) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GroupContentItem) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type BlockListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId     string `protobuf:"bytes,1,opt,name=GroupId,json=groupId,proto3" json:"GroupId,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=UserId,json=userId,proto3" json:"UserId,omitempty"`
	OwnerPubkey string `protobuf:"bytes,3,opt,name=OwnerPubkey,json=ownerPubkey,proto3" json:"OwnerPubkey,omitempty"`
	OwnerSign   string `protobuf:"bytes,4,opt,name=OwnerSign,json=ownerSign,proto3" json:"OwnerSign,omitempty"`
	Memo        string `protobuf:"bytes,5,opt,name=Memo,json=memo,proto3" json:"Memo,omitempty"`
	TimeStamp   int64  `protobuf:"varint,6,opt,name=TimeStamp,json=timeStamp,proto3" json:"TimeStamp,omitempty"`
}

func (x *BlockListItem) Reset() {
	*x = BlockListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockListItem) ProtoMessage() {}

func (x *BlockListItem) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockListItem.ProtoReflect.Descriptor instead.
func (*BlockListItem) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{11}
}

func (x *BlockListItem) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *BlockListItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BlockListItem) GetOwnerPubkey() string {
	if x != nil {
		return x.OwnerPubkey
	}
	return ""
}

func (x *BlockListItem) GetOwnerSign() string {
	if x != nil {
		return x.OwnerSign
	}
	return ""
}

func (x *BlockListItem) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *BlockListItem) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

var File_chain_proto protoreflect.FileDescriptor

var file_chain_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x71,
	0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62, 0x22, 0xf6, 0x01, 0x0a, 0x06, 0x54, 0x72, 0x78,
	0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x72, 0x78, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x72, 0x78, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x72, 0x78, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x69, 0x67,
	0x6e, 0x22, 0x5c, 0x0a, 0x03, 0x54, 0x72, 0x78, 0x12, 0x23, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x72, 0x78, 0x4d, 0x73, 0x67, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x22,
	0x45, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61,
	0x74, 0x61, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x97, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x53, 0x69,
	0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x54, 0x72, 0x78,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x71, 0x54, 0x72, 0x78,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x57, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x77, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x20,
	0x0a, 0x0b, 0x57, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x77, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x69, 0x67, 0x6e,
	0x22, 0xad, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x4e, 0x65, 0x78, 0x74, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x2f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x71, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x22, 0xa5, 0x02, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x76, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x65,
	0x76, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f,
	0x75, 0x73, 0x48, 0x61, 0x73, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72,
	0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x54, 0x72, 0x78, 0x73, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x54,
	0x72, 0x78, 0x52, 0x04, 0x74, 0x72, 0x78, 0x73, 0x22, 0x54, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6e,
	0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0x28,
	0x0a, 0x0c, 0x52, 0x65, 0x71, 0x4e, 0x65, 0x78, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x18,
	0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x22, 0x89, 0x02, 0x0a, 0x09, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x50,
	0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e,
	0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x24, 0x0a, 0x0d, 0x4c, 0x61, 0x74, 0x65,
	0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x34,
	0x0a, 0x0c, 0x47, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0c, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x7e, 0x0a, 0x10, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x72, 0x78, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x72, 0x78, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x6d, 0x70, 0x22, 0xb3, 0x01, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x65, 0x6d, 0x6f,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x12, 0x1c, 0x0a, 0x09,
	0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x2a, 0x95, 0x01, 0x0a, 0x07, 0x54,
	0x72, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x51, 0x5f, 0x53, 0x49,
	0x47, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45, 0x51, 0x5f, 0x53, 0x49, 0x47, 0x4e,
	0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x44, 0x44, 0x5f, 0x4e,
	0x45, 0x57, 0x5f, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x44,
	0x44, 0x5f, 0x4e, 0x45, 0x57, 0x5f, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x52, 0x45, 0x53, 0x50,
	0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x51, 0x5f, 0x4e, 0x45, 0x58, 0x54, 0x5f, 0x42,
	0x4c, 0x4f, 0x43, 0x4b, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x51, 0x5f, 0x4e, 0x45,
	0x58, 0x54, 0x5f, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x05, 0x12,
	0x11, 0x0a, 0x0d, 0x50, 0x45, 0x45, 0x52, 0x5f, 0x41, 0x4e, 0x4e, 0x4f, 0x55, 0x4e, 0x43, 0x45,
	0x10, 0x06, 0x2a, 0x2e, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10,
	0x0a, 0x0c, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x49, 0x4e, 0x5f, 0x54, 0x52, 0x58, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x4f, 0x4e, 0x5f, 0x54, 0x4f, 0x50,
	0x10, 0x01, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x68, 0x75, 0x6f, 0x2d, 0x6a, 0x75, 0x2f, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chain_proto_rawDescOnce sync.Once
	file_chain_proto_rawDescData = file_chain_proto_rawDesc
)

func file_chain_proto_rawDescGZIP() []byte {
	file_chain_proto_rawDescOnce.Do(func() {
		file_chain_proto_rawDescData = protoimpl.X.CompressGZIP(file_chain_proto_rawDescData)
	})
	return file_chain_proto_rawDescData
}

var file_chain_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chain_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_chain_proto_goTypes = []interface{}{
	(TrxType)(0),             // 0: quorum.pb.TrxType
	(ReqBlock)(0),            // 1: quorum.pb.ReqBlock
	(*TrxMsg)(nil),           // 2: quorum.pb.TrxMsg
	(*Trx)(nil),              // 3: quorum.pb.Trx
	(*ReqSign)(nil),          // 4: quorum.pb.ReqSign
	(*ReqSignResp)(nil),      // 5: quorum.pb.ReqSignResp
	(*ReqNextBlockResp)(nil), // 6: quorum.pb.ReqNextBlockResp
	(*Block)(nil),            // 7: quorum.pb.Block
	(*NewBlock)(nil),         // 8: quorum.pb.NewBlock
	(*NewBlockResp)(nil),     // 9: quorum.pb.NewBlockResp
	(*ReqNextBlock)(nil),     // 10: quorum.pb.ReqNextBlock
	(*GroupItem)(nil),        // 11: quorum.pb.GroupItem
	(*GroupContentItem)(nil), // 12: quorum.pb.GroupContentItem
	(*BlockListItem)(nil),    // 13: quorum.pb.BlockListItem
}
var file_chain_proto_depIdxs = []int32{
	0, // 0: quorum.pb.TrxMsg.MsgType:type_name -> quorum.pb.TrxType
	2, // 1: quorum.pb.Trx.Msg:type_name -> quorum.pb.TrxMsg
	1, // 2: quorum.pb.ReqNextBlockResp.Response:type_name -> quorum.pb.ReqBlock
	3, // 3: quorum.pb.Block.Trxs:type_name -> quorum.pb.Trx
	7, // 4: quorum.pb.GroupItem.GenesisBlock:type_name -> quorum.pb.Block
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_chain_proto_init() }
func file_chain_proto_init() {
	if File_chain_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chain_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrxMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chain_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chain_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chain_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSignResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chain_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqNextBlockResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chain_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chain_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chain_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewBlockResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chain_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqNextBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chain_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chain_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupContentItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chain_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chain_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chain_proto_goTypes,
		DependencyIndexes: file_chain_proto_depIdxs,
		EnumInfos:         file_chain_proto_enumTypes,
		MessageInfos:      file_chain_proto_msgTypes,
	}.Build()
	File_chain_proto = out.File
	file_chain_proto_rawDesc = nil
	file_chain_proto_goTypes = nil
	file_chain_proto_depIdxs = nil
}
