package cmd

import (
	"fmt"

	"github.com/labstack/echo/v4"
	"github.com/spf13/cobra"

	echoSwagger "github.com/swaggo/echo-swagger"

	_ "github.com/rumsystem/quorum/docs" // docs is generated by Swag CLI, you have to import it.
)

var docsPort uint

// docsCmd represents the docs command
var docsCmd = &cobra.Command{
	Use:   "docs",
	Short: "Serve the swagger docs",
	Run: func(cmd *cobra.Command, args []string) {
		e := echo.New()
		e.HideBanner = true
		e.GET("/*", echoSwagger.WrapHandler)

		e.Logger.Fatal(e.Start(fmt.Sprintf(":%d", docsPort)))
	},
}

func init() {
	rootCmd.AddCommand(docsCmd)

	flags := docsCmd.Flags()
	flags.SortFlags = false
	flags.UintVarP(&docsPort, "port", "p", 1323, "listen port")
}
