// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.12
// source: rumexchange.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RumDataMsgType int32

const (
	RumDataMsgType_CHAIN_DATA RumDataMsgType = 0
)

// Enum value maps for RumDataMsgType.
var (
	RumDataMsgType_name = map[int32]string{
		0: "CHAIN_DATA",
	}
	RumDataMsgType_value = map[string]int32{
		"CHAIN_DATA": 0,
	}
)

func (x RumDataMsgType) Enum() *RumDataMsgType {
	p := new(RumDataMsgType)
	*p = x
	return p
}

func (x RumDataMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RumDataMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_rumexchange_proto_enumTypes[0].Descriptor()
}

func (RumDataMsgType) Type() protoreflect.EnumType {
	return &file_rumexchange_proto_enumTypes[0]
}

func (x RumDataMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RumDataMsgType.Descriptor instead.
func (RumDataMsgType) EnumDescriptor() ([]byte, []int) {
	return file_rumexchange_proto_rawDescGZIP(), []int{0}
}

type RumDataMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType     RumDataMsgType `protobuf:"varint,1,opt,name=MsgType,proto3,enum=quorum.pb.RumDataMsgType" json:"MsgType,omitempty"`
	DataPackage *Package       `protobuf:"bytes,2,opt,name=DataPackage,proto3,oneof" json:"DataPackage,omitempty"`
}

func (x *RumDataMsg) Reset() {
	*x = RumDataMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rumexchange_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RumDataMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RumDataMsg) ProtoMessage() {}

func (x *RumDataMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rumexchange_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RumDataMsg.ProtoReflect.Descriptor instead.
func (*RumDataMsg) Descriptor() ([]byte, []int) {
	return file_rumexchange_proto_rawDescGZIP(), []int{0}
}

func (x *RumDataMsg) GetMsgType() RumDataMsgType {
	if x != nil {
		return x.MsgType
	}
	return RumDataMsgType_CHAIN_DATA
}

func (x *RumDataMsg) GetDataPackage() *Package {
	if x != nil {
		return x.DataPackage
	}
	return nil
}

var File_rumexchange_proto protoreflect.FileDescriptor

var file_rumexchange_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x75, 0x6d, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62, 0x1a, 0x0b,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x0a,
	0x52, 0x75, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x12, 0x33, 0x0a, 0x07, 0x4d, 0x73,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x71, 0x75,
	0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x75, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x4d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x39, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x44, 0x61, 0x74, 0x61,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x44,
	0x61, 0x74, 0x61, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2a, 0x20, 0x0a, 0x0e, 0x52, 0x75,
	0x6d, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a,
	0x43, 0x48, 0x41, 0x49, 0x4e, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x00, 0x42, 0x24, 0x5a, 0x22,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x75, 0x6d, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2f, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rumexchange_proto_rawDescOnce sync.Once
	file_rumexchange_proto_rawDescData = file_rumexchange_proto_rawDesc
)

func file_rumexchange_proto_rawDescGZIP() []byte {
	file_rumexchange_proto_rawDescOnce.Do(func() {
		file_rumexchange_proto_rawDescData = protoimpl.X.CompressGZIP(file_rumexchange_proto_rawDescData)
	})
	return file_rumexchange_proto_rawDescData
}

var file_rumexchange_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rumexchange_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rumexchange_proto_goTypes = []interface{}{
	(RumDataMsgType)(0), // 0: quorum.pb.RumDataMsgType
	(*RumDataMsg)(nil),  // 1: quorum.pb.RumDataMsg
	(*Package)(nil),     // 2: quorum.pb.Package
}
var file_rumexchange_proto_depIdxs = []int32{
	0, // 0: quorum.pb.RumDataMsg.MsgType:type_name -> quorum.pb.RumDataMsgType
	2, // 1: quorum.pb.RumDataMsg.DataPackage:type_name -> quorum.pb.Package
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rumexchange_proto_init() }
func file_rumexchange_proto_init() {
	if File_rumexchange_proto != nil {
		return
	}
	file_chain_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rumexchange_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RumDataMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rumexchange_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rumexchange_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rumexchange_proto_goTypes,
		DependencyIndexes: file_rumexchange_proto_depIdxs,
		EnumInfos:         file_rumexchange_proto_enumTypes,
		MessageInfos:      file_rumexchange_proto_msgTypes,
	}.Build()
	File_rumexchange_proto = out.File
	file_rumexchange_proto_rawDesc = nil
	file_rumexchange_proto_goTypes = nil
	file_rumexchange_proto_depIdxs = nil
}
